### ISSUE TITLE
PA User Auth

### ISSUE THREAD

**Issue by rkoron007** [nathashas1/FULL-STACK#7]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [x] When errors are displayed, the input boxes should not move
- [x] Smooth, bug free navigation
  - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
  - [x] Errors should display for both `/signup` and`/login`.
  - [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Adequate and appropriate seeds
  - [x] Demo Login Works

**Comment by nathashas1** [comment]
Completed UserAuth

**Comment by rkoron007** [comment]
Make sure you put your heroku link on your wiki page :)

**Comment by nathashas1** [comment]
Added the link to heroku!

**Comment by rkoron007** [comment]
I think the link is to your dashboard and not your live site? Try going to your live site that will look something like this: `https://atsea.herokuapp.com/` and add that link. Let me know when you do :)

**Comment by nathashas1** [comment]
I have updated the link with the live site.

**Comment by rkoron007** [comment]
Once you have errors rendering can you re-assign me to review this?  A lot of these check boxes do have to with how errors are being handled :)

**Comment by nathashas1** [comment]
I did fix the errors part.It renders errors for incorrect username and password for log in and sign up.let me know if there is more to this.

**Comment by rkoron007** [comment]
![screen shot 2018-10-17 at 9 13 39 am](https://user-images.githubusercontent.com/32436232/47100697-010ec680-d1ed-11e8-9fd4-63fce90570f1.png)
- Maybe you didn't push the error rendering to Heroku yet? When I try to submit the sign up with no password I see a 500 request error and no errors on the page.

**Comment by nathashas1** [comment]
Oh Iam sorry.It was not rendering properly.
I fixed that now. But the errors are not disappearing from when we go from
login page to sign up unless you refresh.Iam working on that now.I will let
you know once i am done.
Could you tell me like how will i do it?
( To make the error disappear?)

**Comment by rkoron007** [comment]
You can probably use something like this in your container : 
`clearErrors: () => dispatch(receiveErrors([]))`
- Then call it whenever the component  is Unmounting(since that means the form is leaving the page) . Since you know the default state of your session Error Reducer is an empty array then you can can dispatch the ***action***(not the action creator) with an empty array to reset your Session Error's slice of state.

**Comment by rkoron007** [comment]
- Make sure that I can go to a random route and it will redirect you to `/`,` /login`, or `/signup`. (Hint: you can use a Switch with a Redirect at the bottom (from React Router) to achieve this effect).

- Make a logout Button a user can test logging out and back in? You can just put it in your Navbar :)

## Styling:
- ![screen shot 2018-10-18 at 9 57 10 am](https://user-images.githubusercontent.com/32436232/47170919-3d5d2800-d2bc-11e8-9138-04b506870d5b.png)

- Maybe put an image tag with the rabbit for your login form?
---
![screen shot 2018-10-18 at 9 51 03 am](https://user-images.githubusercontent.com/32436232/47170635-616c3980-d2bb-11e8-8d92-1b2dae74ed7f.png)
- I think the text in the button for `Becoming a Tasker` could move down a little to be right in the center.

**Comment by nathashas1** [comment]
Hi Rose,

I have made those changes, if you could review it.

**Comment by rkoron007** [comment]
![screen shot 2018-10-18 at 1 34 06 pm](https://user-images.githubusercontent.com/32436232/47182566-9b006d00-d2da-11e8-8462-93a0a044b602.png)
- It looks like I can go to a random route but it isn't redirecting back to `/`,` /login`, or `/signup`.

- It also looks like button text isn't quite centered yet?
![screen shot 2018-10-18 at 1 37 00 pm](https://user-images.githubusercontent.com/32436232/47182686-e74bad00-d2da-11e8-92ad-a54709c5bdff.png)

**Comment by rkoron007** [comment]
Great job!!
